strictness: veryhigh

max-line-length: 79

autodetect: false

ignore-paths:
  - doc

pylint:
    options:
        additional-builtins:
            - NS

pyroma:
  run: true

pyflakes:
  disable:
    # F821: undefined name; caught better by pylint, where it can be
    # controlled for the whole file/per-line
    - F821
